config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'

  namespace :home do
      get :index
      get :register
      get :logout
      post :login
      post :create_user
  end
    get '/home', :controller => "home", :action => "index" 

   namespace :resources do 
      get :index
      get :viewResource
      get :collectMoney
      post :buyResource
  end
    get '/resources', :controller => "resources", :action => "index" 
    get 'resources/viewResource/:id' => 'resources#viewResource'
    get 'resources/collectMoney/:id' => 'resources#collectMoney'

  namespace :tutorial do
      get :index
      get :step2
      post :compleate
  end
    get '/tutorial', :controller => "tutorial", :action => "index" 

  namespace :inventory do
      get :index
      get :collect_loot
      post :updateInventory
  end
    get '/inventory', :controller => "inventory", :action => "index" 

  get "/admin", :controller => "admin", :action => "dashboard"
    namespace :admin do
      resources :users
    end

    namespace :admin do
      resources :player_characters
    end

    namespace :admin do
      resources :recreationals_categories
    end

    namespace :admin do
      resources :recreational_resources
    end

    namespace :admin do
      resources :inventory_items
    end

end

app/models/admin/inventory_item.rb
class Admin::InventoryItem < ActiveRecord::Base
end

app/controllers/admin/inventory_items_controller.rb
class Admin::InventoryItemsController < ApplicationController
  before_filter :is_admin
  before_action :set_admin_inventory_item, only: [:show, :edit, :update, :destroy]

  # GET /admin/inventory_items
  # GET /admin/inventory_items.json
  def index
    @admin_inventory_items = Admin::InventoryItem.all
  end

  # GET /admin/inventory_items/1
  # GET /admin/inventory_items/1.json
  def show
  end

  # GET /admin/inventory_items/new
  def new
    @admin_inventory_item = Admin::InventoryItem.new
  end

  # GET /admin/inventory_items/1/edit
  def edit
  end

  # POST /admin/inventory_items
  # POST /admin/inventory_items.json
  def create
    @admin_inventory_item = Admin::InventoryItem.new(admin_inventory_item_params)

    respond_to do |format|
      if @admin_inventory_item.save
        format.html { redirect_to @admin_inventory_item, notice: 'Inventory item was successfully created.' }
        format.json { render :show, status: :created, location: @admin_inventory_item }
      else
        format.html { render :new }
        format.json { render json: @admin_inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/inventory_items/1
  # PATCH/PUT /admin/inventory_items/1.json
  def update
    respond_to do |format|
      if @admin_inventory_item.update(admin_inventory_item_params)
        format.html { redirect_to @admin_inventory_item, notice: 'Inventory item was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_inventory_item }
      else
        format.html { render :edit }
        format.json { render json: @admin_inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/inventory_items/1
  # DELETE /admin/inventory_items/1.json
  def destroy
    @admin_inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to admin_inventory_items_url, notice: 'Inventory item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_inventory_item
      @admin_inventory_item = Admin::InventoryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_inventory_item_params
      params.require(:admin_inventory_item).permit(:name, :image, :status)
    end
end

app/helpers/admin/inventory_items_helper.rb
module Admin::InventoryItemsHelper
end

app/views/admin/inventory_items/_form.html.haml
= form_for @admin_inventory_item do |f|
  - if @admin_inventory_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_inventory_item.errors.count, "error")} prohibited this admin_inventory_item from being saved:"
      %ul
        - @admin_inventory_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :status
    = f.number_field :status
  .actions
    = f.submit 'Save'

app/views/admin/inventory_items/edit.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } View #{@admin_inventory_item.name}

	%div{ :class => "panel-body" }

		= render 'form'

		= link_to 'Show', @admin_inventory_item
		\|
		= link_to 'Back', admin_inventory_items_path

app/views/admin/inventory_items/index.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

  %div{ :class => "panel-heading" } Listing Characters

  %div{ :class => "panel-body" }

    %table{ :class => "table" }
      %tr
        %th Name
        %th Image
        %th Status
        %th
        %th
        %th

      - @admin_inventory_items.each do |admin_inventory_item|
        %tr
          %td= admin_inventory_item.name
          %td= admin_inventory_item.image
          %td= admin_inventory_item.status
          %td= link_to 'Show', admin_inventory_item
          %td= link_to 'Edit', edit_admin_inventory_item_path(admin_inventory_item)
          %td= link_to 'Destroy', admin_inventory_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Inventory item', new_admin_inventory_item_path

app/views/admin/inventory_items/new.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } Create new Inventory item

	%div{ :class => "panel-body" }

		= render 'form'

		= link_to 'Back', admin_inventory_items_path

app/views/admin/inventory_items/show.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } View #{@admin_inventory_item.name}

	%div{ :class => "panel-body" }
		%p#notice= notice
		%p
		%b Name:
		= @admin_inventory_item.name
		%p
		%b Image:
		= @admin_inventory_item.image
		%p
		%b Status:
		= @admin_inventory_item.status

		= link_to 'Edit', edit_admin_inventory_item_path(@admin_inventory_item)
		\|
		= link_to 'Back', admin_inventory_items_path