config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'

  namespace :home do
      get :index
      get :register
      get :logout
      post :login
      post :create_user
  end
    get '/home', :controller => "home", :action => "index" 

   namespace :resources do 
      get :index
      get :viewResource
      get :collectMoney
      post :buyResource
  end
    get '/resources', :controller => "resources", :action => "index" 
    get 'resources/viewResource/:id' => 'resources#viewResource'
    get 'resources/collectMoney/:id' => 'resources#collectMoney'

  namespace :tutorial do
      get :index
      get :step2
      post :compleate
  end
    get '/tutorial', :controller => "tutorial", :action => "index" 

  namespace :inventory do
      get :index
      get :collect_loot
      post :updateInventory
  end
    get '/inventory', :controller => "inventory", :action => "index" 

  get "/admin", :controller => "admin", :action => "dashboard"
    namespace :admin do
      resources :users
    end

    namespace :admin do
      resources :player_characters
    end

    namespace :admin do
      resources :recreationals_categories
    end

    namespace :admin do
      resources :recreational_resources
    end

    namespace :admin do
      resources :inventory_items
    end

end

app/models/admin/recreationals_category.rb
class Admin::RecreationalsCategory < ActiveRecord::Base

	def self.getReacteanalCategoryName id
		# Fetches Category with id
		getCategoryName = Admin::RecreationalsCategory.find_by_id(id)
		# Return category name
		getCategoryName.name
	end

end

app/controllers/admin/recreationals_categories_controller.rb
class Admin::RecreationalsCategoriesController < ApplicationController
  before_filter :is_admin
  before_action :set_admin_recreationals_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/recreationals_categories
  # GET /admin/recreationals_categories.json
  def index
    @admin_recreationals_categories = Admin::RecreationalsCategory.all
  end

  # GET /admin/recreationals_categories/1
  # GET /admin/recreationals_categories/1.json
  def show
  end

  # GET /admin/recreationals_categories/new
  def new
    @admin_recreationals_category = Admin::RecreationalsCategory.new
  end

  # GET /admin/recreationals_categories/1/edit
  def edit
  end

  # POST /admin/recreationals_categories
  # POST /admin/recreationals_categories.json
  def create
    @admin_recreationals_category = Admin::RecreationalsCategory.new(admin_recreationals_category_params)

    respond_to do |format|
      if @admin_recreationals_category.save
        format.html { redirect_to @admin_recreationals_category, notice: 'Recreationals category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_recreationals_category }
      else
        format.html { render :new }
        format.json { render json: @admin_recreationals_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/recreationals_categories/1
  # PATCH/PUT /admin/recreationals_categories/1.json
  def update
    respond_to do |format|
      if @admin_recreationals_category.update(admin_recreationals_category_params)
        format.html { redirect_to @admin_recreationals_category, notice: 'Recreationals category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_recreationals_category }
      else
        format.html { render :edit }
        format.json { render json: @admin_recreationals_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/recreationals_categories/1
  # DELETE /admin/recreationals_categories/1.json
  def destroy
    @admin_recreationals_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_recreationals_categories_url, notice: 'Recreationals category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_recreationals_category
      @admin_recreationals_category = Admin::RecreationalsCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_recreationals_category_params
      params.require(:admin_recreationals_category).permit(:name, :description, :image, :status)
    end
end

app/helpers/admin/recreationals_categories_helper.rb
module Admin::RecreationalsCategoriesHelper
end

app/views/admin/recreationals_categories/_form.html.haml
= form_for @admin_recreationals_category do |f|
  - if @admin_recreationals_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_recreationals_category.errors.count, "error")} prohibited this admin_recreationals_category from being saved:"
      %ul
        - @admin_recreationals_category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/admin/recreationals_categories/edit.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } Edit #{@admin_recreationals_category.name}

	%div{ :class => "panel-body" }

		= render 'form'

		= link_to 'Show', @admin_recreationals_category
		\|
		= link_to 'Back', admin_recreationals_categories_path

app/views/admin/recreationals_categories/index.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

  %div{ :class => "panel-heading" } Recreational categories

  %div{ :class => "panel-body" }

    %table{ :class => "table" }
      %tr
        %th Name
        %th Description
        %th Image
        %th Status
        %th
        %th
        %th

      - @admin_recreationals_categories.each do |admin_recreationals_category|
        %tr
          %td= admin_recreationals_category.name
          %td= admin_recreationals_category.description
          %td= admin_recreationals_category.image
          %td= admin_recreationals_category.status
          %td= link_to 'Show', admin_recreationals_category
          %td= link_to 'Edit', edit_admin_recreationals_category_path(admin_recreationals_category)
          %td= link_to 'Destroy', admin_recreationals_category, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Recreationals category', new_admin_recreationals_category_path

    | 

    = link_to "Administer Recreational resources", "/admin/recreational_resources"

app/views/admin/recreationals_categories/new.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } Create new Character type

	%div{ :class => "panel-body" }

		= render 'form'

		= link_to 'Back', admin_recreationals_categories_path

app/views/admin/recreationals_categories/show.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } Edit #{@admin_recreationals_category.name}

	%div{ :class => "panel-body" }
		%p#notice= notice
		%b Name:
		= @admin_recreationals_category.name
		%p
		%b Description:
		= @admin_recreationals_category.description
		%p
		%b Image:
		= @admin_recreationals_category.image
		%p
		%b Status:
		= @admin_recreationals_category.status

		= link_to 'Edit', edit_admin_recreationals_category_path(@admin_recreationals_category)
		\|
		= link_to 'Back', admin_recreationals_categories_path