config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'

  namespace :home do
      get :index
      get :register
      get :logout
      post :login
      post :create_user
  end
    get '/home', :controller => "home", :action => "index" 

   namespace :resources do 
      get :index
      get :viewResource
      get :collectMoney
      post :buyResource
  end
    get '/resources', :controller => "resources", :action => "index" 
    get 'resources/viewResource/:id' => 'resources#viewResource'
    get 'resources/collectMoney/:id' => 'resources#collectMoney'

  namespace :tutorial do
      get :index
      get :step2
      post :compleate
  end
    get '/tutorial', :controller => "tutorial", :action => "index" 

  namespace :inventory do
      get :index
      get :collect_loot
      post :updateInventory
  end
    get '/inventory', :controller => "inventory", :action => "index" 

  get "/admin", :controller => "admin", :action => "dashboard"
    namespace :admin do
      resources :users
    end

    namespace :admin do
      resources :player_characters
    end

    namespace :admin do
      resources :recreationals_categories
    end

    namespace :admin do
      resources :recreational_resources
    end

    namespace :admin do
      resources :inventory_items
    end

end

app/models/admin/player_character.rb
class Admin::PlayerCharacter < ActiveRecord::Base

	def self.GetPlayerCharacterName id
		# Fetches Character
		get_name = Admin::PlayerCharacter.find_by_id(id)
		# return name
		get_name.name
	end

end

app/controllers/admin/player_characters_controller.rb
class Admin::PlayerCharactersController < ApplicationController
  before_filter :is_admin
  before_action :set_admin_player_character, only: [:show, :edit, :update, :destroy]

  # GET /admin/player_characters
  # GET /admin/player_characters.json
  def index
    @admin_player_characters = Admin::PlayerCharacter.all
  end

  # GET /admin/player_characters/1
  # GET /admin/player_characters/1.json
  def show
  end

  # GET /admin/player_characters/new
  def new
    @admin_player_character = Admin::PlayerCharacter.new
  end

  # GET /admin/player_characters/1/edit
  def edit
  end

  # POST /admin/player_characters
  # POST /admin/player_characters.json
  def create
    @admin_player_character = Admin::PlayerCharacter.new(admin_player_character_params)

    respond_to do |format|
      if @admin_player_character.save
        format.html { redirect_to @admin_player_character, notice: 'Player character was successfully created.' }
        format.json { render :show, status: :created, location: @admin_player_character }
      else
        format.html { render :new }
        format.json { render json: @admin_player_character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/player_characters/1
  # PATCH/PUT /admin/player_characters/1.json
  def update
    respond_to do |format|
      if @admin_player_character.update(admin_player_character_params)
        format.html { redirect_to @admin_player_character, notice: 'Player character was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_player_character }
      else
        format.html { render :edit }
        format.json { render json: @admin_player_character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/player_characters/1
  # DELETE /admin/player_characters/1.json
  def destroy
    @admin_player_character.destroy
    respond_to do |format|
      format.html { redirect_to admin_player_characters_url, notice: 'Player character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_player_character
      @admin_player_character = Admin::PlayerCharacter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_player_character_params
      params.require(:admin_player_character).permit(:name, :description, :image)
    end
end

app/helpers/admin/player_characters_helper.rb
module Admin::PlayerCharactersHelper
end

app/views/admin/player_characters/_form.html.haml
= form_for @admin_player_character do |f|
  - if @admin_player_character.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_player_character.errors.count, "error")} prohibited this admin_player_character from being saved:"
      %ul
        - @admin_player_character.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/admin/player_characters/edit.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } View #{@admin_player_character.name}

	%div{ :class => "panel-body" }

		= render 'form'

		= link_to 'Show', @admin_player_character
		\|
		= link_to 'Back', admin_player_characters_path

app/views/admin/player_characters/index.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

  %div{ :class => "panel-heading" } Listing Characters

  %div{ :class => "panel-body" }

    %table{ :class => "table" }
      %tr
        %th Name
        %th Description
        %th Image
        %th
        %th
        %th

      - @admin_player_characters.each do |admin_player_character|
        %tr
          %td= admin_player_character.name
          %td= admin_player_character.description
          %td= admin_player_character.image
          %td= link_to 'Show', admin_player_character
          %td= link_to 'Edit', edit_admin_player_character_path(admin_player_character)
          %td= link_to 'Destroy', admin_player_character, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Player character', new_admin_player_character_path

app/views/admin/player_characters/new.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } Create new Character type

	%div{ :class => "panel-body" }

		= render 'form'

		= link_to 'Back', admin_player_characters_path

app/views/admin/player_characters/show.html.haml
#{render partial:"admin/adminmenu"}

%br

%div{ :class => "panel panel-primary" }

	%div{ :class => "panel-heading" } View #{@admin_player_character.name}

	%div{ :class => "panel-body" }
		%p#notice= notice
		%p
		%b Name:
		= @admin_player_character.name
		%p
		%b Description:
		= @admin_player_character.description
		%p
		%b Image:
		= @admin_player_character.image

		= link_to 'Edit', edit_admin_player_character_path(@admin_player_character)
		\|
		= link_to 'Back', admin_player_characters_path